# Logistic Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [5]:
print(X_train)

[[    31  34000]
 [    42  73000]
 [    46  23000]
 [    44  39000]
 [    35  20000]
 [    21  88000]
 [    35 108000]
 [    47  25000]
 [    41  30000]
 [    48  96000]
 [    38  61000]
 [    59  42000]
 [    41  63000]
 [    27  96000]
 [    52 138000]
 [    41  45000]
 [    24  55000]
 [    28  37000]
 [    39  75000]
 [    41  51000]
 [    29  43000]
 [    37  71000]
 [    40 142000]
 [    24  27000]
 [    33  60000]
 [    35  39000]
 [    60  42000]
 [    37  57000]
 [    41  72000]
 [    23  48000]
 [    27  20000]
 [    53  82000]
 [    31  68000]
 [    32 150000]
 [    27  90000]
 [    40  65000]
 [    53  72000]
 [    24  84000]
 [    47  50000]
 [    37 146000]
 [    42  80000]
 [    41  60000]
 [    53 104000]
 [    41  79000]
 [    18  68000]
 [    35  58000]
 [    25  90000]
 [    21  72000]
 [    32  18000]
 [    18  52000]
 [    38 112000]
 [    48  35000]
 [    47  34000]
 [    47  23000]
 [    34 115000]
 [    37  77000]
 [    49  39000]
 [    20  23000]
 [    35  8800

In [6]:
print(y_train)

[0 1 1 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1
 0 1 1 1 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0
 0 0 1 0 0 1 1 1 1 0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 1 0 0 0 1 0 1 1 0 1 0 0 0
 0 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 1 0 0 1 1 1
 0 0 1 0 0 1 1 0 1 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 1 1 0 0 1 0 1 1 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 1 0
 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0 1 0 0 1 1 0 1 1 0 0 1 1 1 0 0 0 1 0 0 0 0 1
 0 1 0 1]


In [7]:
print(X_test)

[[    39  71000]
 [    28 123000]
 [    39 106000]
 [    57 122000]
 [    41  59000]
 [    37  93000]
 [    59  83000]
 [    40  61000]
 [    33  69000]
 [    34  43000]
 [    28  84000]
 [    47 144000]
 [    49  88000]
 [    48 119000]
 [    27  57000]
 [    26  30000]
 [    24  32000]
 [    40  75000]
 [    27  58000]
 [    40  72000]
 [    41  80000]
 [    37  62000]
 [    35  53000]
 [    45  22000]
 [    33  28000]
 [    50  20000]
 [    41  72000]
 [    46  41000]
 [    23  66000]
 [    29  61000]
 [    19  19000]
 [    19  25000]
 [    35  57000]
 [    37  53000]
 [    38  80000]
 [    36  50000]
 [    45 131000]
 [    52 150000]
 [    36 118000]
 [    22  55000]
 [    39  73000]
 [    48  29000]
 [    41  72000]
 [    38  65000]
 [    38  51000]
 [    52  38000]
 [    46  22000]
 [    40  57000]
 [    32 117000]
 [    56  60000]
 [    40  59000]
 [    35  50000]
 [    32 117000]
 [    35  79000]
 [    35  23000]
 [    35  55000]
 [    46  82000]
 [    35 147000]
 [    42  7500

In [8]:
print(y_test)

[0 1 1 1 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1
 1 1 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 1 1 0
 0 0 1 1 0 0 0 1 1 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 0]


## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
print(X_train)

[[-0.60725525 -1.06085085]
 [ 0.4068856   0.09871146]
 [ 0.7756641  -1.38790688]
 [ 0.59127485 -0.91218902]
 [-0.23847676 -1.47710399]
 [-1.52920148  0.54469696]
 [-0.23847676  1.1393443 ]
 [ 0.86785872 -1.32844215]
 [ 0.31469098 -1.17978032]
 [ 0.96005334  0.7825559 ]
 [ 0.03810711 -0.25807694]
 [ 1.97419419 -0.82299191]
 [ 0.31469098 -0.19861221]
 [-0.97603374  0.7825559 ]
 [ 1.32883183  2.0313153 ]
 [ 0.31469098 -0.73379481]
 [-1.25261761 -0.43647115]
 [-0.88383912 -0.97165375]
 [ 0.13030173  0.15817619]
 [ 0.31469098 -0.55540061]
 [-0.7916445  -0.79325955]
 [-0.05408751  0.03924672]
 [ 0.22249636  2.15024477]
 [-1.25261761 -1.26897742]
 [-0.422866   -0.28780931]
 [-0.23847676 -0.91218902]
 [ 2.06638882 -0.82299191]
 [-0.05408751 -0.37700641]
 [ 0.31469098  0.06897909]
 [-1.34481223 -0.64459771]
 [-0.97603374 -1.47710399]
 [ 1.42102646  0.36630276]
 [-0.60725525 -0.04995038]
 [-0.51506063  2.38810371]
 [-0.97603374  0.60416169]
 [ 0.22249636 -0.13914748]
 [ 1.42102646  0.06897909]
 

In [11]:
print(X_test)

[[ 0.13030173  0.03924672]
 [-0.88383912  1.5853298 ]
 [ 0.13030173  1.07987956]
 [ 1.78980495  1.55559743]
 [ 0.31469098 -0.31754168]
 [-0.05408751  0.6933588 ]
 [ 1.97419419  0.39603513]
 [ 0.22249636 -0.25807694]
 [-0.422866   -0.02021801]
 [-0.33067138 -0.79325955]
 [-0.88383912  0.42576749]
 [ 0.86785872  2.2097095 ]
 [ 1.05224796  0.54469696]
 [ 0.96005334  1.46640033]
 [-0.97603374 -0.37700641]
 [-1.06822837 -1.17978032]
 [-1.25261761 -1.12031558]
 [ 0.22249636  0.15817619]
 [-0.97603374 -0.34727404]
 [ 0.22249636  0.06897909]
 [ 0.31469098  0.30683803]
 [-0.05408751 -0.22834458]
 [-0.23847676 -0.49593588]
 [ 0.68346947 -1.41763925]
 [-0.422866   -1.23924505]
 [ 1.14444259 -1.47710399]
 [ 0.31469098  0.06897909]
 [ 0.7756641  -0.85272428]
 [-1.34481223 -0.10941511]
 [-0.7916445  -0.25807694]
 [-1.71359073 -1.50683635]
 [-1.71359073 -1.32844215]
 [-0.23847676 -0.37700641]
 [-0.05408751 -0.49593588]
 [ 0.03810711  0.30683803]
 [-0.14628214 -0.58513298]
 [ 0.68346947  1.82318874]
 

## Training the Logistic Regression model on the Training set

In [12]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

## Predicting a new result

In [17]:
lr.predict(sc.transform([[30, 87000]]))

array([0])

## Predicting the Test set results

In [23]:
y_pred = lr.predict(X_test)
print(y_test, y_pred)

[0 1 1 1 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1
 1 1 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 1 1 0
 0 0 1 1 0 0 0 1 1 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 0] [0 0 1 1 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1
 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1
 0 0 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1]


## Making the Confusion Matrix

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[61  6]
 [ 9 24]]


0.85

## Visualising the Training set results

## Visualising the Test set results